### ISSUE TITLE
Enemy behaviour patterns

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/ProjectCage#23]
Use the AI navmesh to dynamically set targets for enemies based on what is happening around them

Through code make a state machine with following states
1. Released
    * Patrol
    * Idle
2. Chasing/Agitated
    * Stalk
    * Chase Food
    * Chase Player
3. Caught
    * Unfed
    * Fed

Be able to transition between Released and Chasing/Agitated based on what is around or in vision of the character.
* Have a check run every second or so to see what is in his radius
* Or have it update whenever a player enters a trigger collider around the animal....

**Comment by swiimii** [comment]
Panda currently has some basic behaviour, found in #35
