### ISSUE TITLE
Fix throwable objects getting immediately caught by client-only players.

### ISSUE THREAD

**Issue by swiimii** [nicholas-maltbie/ProjectCage#37]

**Comment by swiimii** [comment]
Seems to be caused by an authority error. Network players are spawning objects, but the objects are spawned in the wrong location and given no velocity.

**Comment by swiimii** [comment]
Could also be that the item is *hitting the Trigger Collider for the Panda*

**Comment by nicholas-maltbie** [comment]
Also for server only players

**Comment by nicholas-maltbie** [comment]
Resolved for by adding cooldown
