### ISSUE TITLE
Investigate Polygon Colliders

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/ProjectCage#7]
Get some methodology/workflow of generating polygon colliders (either automatically or manually) for an area in a scene. This can be done by hand or by using generated tools. Or maybe by combining smaller colliders or importing from external software.

Whatever is decided, some workflow for making non square/rectangle/circle colliders for objects in the scene.

**Comment by swiimii** [comment]
Polygon colliders are simple to get started. When you add one to an object, it automatically creates an approximate collider, and can be modified similarly to a freeform light.

https://docs.unity3d.com/Manual/class-PolygonCollider2D.html

![image](https://user-images.githubusercontent.com/37094203/106367314-9aefd400-630f-11eb-9842-7b15a429b3ca.png)
> Example of a generated collider.
